import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { startViewer } from "../../../skills/repoaxis/lib/view-server.mjs";
const VIEWER_DIR=fileURLToPath(new URL("../../../skills/repoaxis/viewer/",import.meta.url)),VIEWER_HTML=path.join(VIEWER_DIR,"repoaxis.html"),V47_BASE_SHA="74378ad9bb5b1c5304b989174454d71a38cd1f9c7538a4bff410f35469a01507",V47_PREFIX_SHA="f473d2ef3e7945c03ead7ead99d6df72529a1e034111043fd6eb46925c862673",LIVE_MARK="<!-- V47-R01 LIVE DATA WIRING -->";
function git(root,...args){return execFileSync("git",["-C",root,...args],{encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim()}
function createRepo(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"repoaxis-viewer-"));fs.mkdirSync(path.join(root,"src"),{recursive:true});fs.writeFileSync(path.join(root,"src","util.js"),"export const value = 1;\n");fs.writeFileSync(path.join(root,"src","main.js"),"import { value } from './util.js';\nexport function main(){ return value; }\n");fs.writeFileSync(path.join(root,"src","legacy.js"),"export const legacy = true;\n");git(root,"init","-q","-b","main");git(root,"config","user.name","Repoaxis Viewer Test");git(root,"config","user.email","repoaxis@example.invalid");git(root,"remote","add","origin","git@github.com:example/repoaxis-viewer-fixture.git");git(root,"add",".");git(root,"commit","-qm","fixture");fs.writeFileSync(path.join(root,"src","util.js"),"export const value = 2;\n");fs.rmSync(path.join(root,"src","legacy.js"));git(root,"add","-A");git(root,"commit","-qm","update util and remove legacy");return root}
test("viewer directory is exactly the canonical single-file v47 shell",()=>{assert.deepEqual(fs.readdirSync(VIEWER_DIR).sort(),["repoaxis.html"]);const html=fs.readFileSync(VIEWER_HTML,"utf8"),mark=html.indexOf(LIVE_MARK);assert.ok(mark>0);assert.equal(crypto.createHash("sha256").update(html.slice(0,mark)).digest("hex"),V47_PREFIX_SHA);assert.match(html,/Repository Intelligence Prototype v47/);for(const id of ["structureStage","dependenciesStage","changesStage","graphStage","drawer"])assert.match(html,new RegExp(`id="${id}"`));for(const fn of ["renderOverview","renderDependencies","renderChanges","renderGraph","navigateSelectedTo","openChangeSetGraphV18","impactPathsV21"])assert.match(html,new RegExp(`function ${fn}|${fn}=function`));assert.match(html,/function bootLiveV47\(\)/);assert.match(html,/fetch\('\/api\/index'\)/);assert.match(html,/fetch\('\/api\/meta'\)/);assert.match(html,/fetch\('\/api\/history'\)/);assert.match(html,/rebuildLiveGraphInputsV47/);assert.match(html,/changed=new Set\(changes\.filter\(c=>c\.id!==['"]ghost['"]&&byId\[c\.id\]\?\.type===['"]file['"]\)/);assert.match(html,/connected\.has\(f\.id\)\|\|changed\.has\(f\.id\)/);assert.match(html,/canonicalRoot=raw\.find\(n=>n\.type===['"]folder['"]&&\(n\.path===['"]\.['"]\|\|n\.path===['"]\.\/['"]\)\)/);assert.match(html,/rawParent===canonicalRootId\?['"]root['"]:rawParent/);assert.match(html,/function overviewVisibleBBoxR05\(/);assert.match(html,/OVERVIEW_HELPERS_R05/);assert.match(html,/generation!==overviewGenerationR05/);assert.match(html,/clearOverviewAcquisitionR05\(\);tree\.splice/);assert.match(html,/function frameChangeSetRootsR04\(/);assert.match(html,/openChangeSetGraphR04Base/);assert.match(html,/function structureFocusScopeR02\(/);assert.match(html,/Focused containment ·/);assert.match(html,/function frameGraphSelectionR03\(/);assert.match(html,/navigateSelectedToR03Base/);assert.match(html,/state\.cameras\.graph=/);assert.doesNotMatch(html,/(?:src|href)="\/viewer-/);for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>new Function(m[1]))});
test("viewer server serves canonical shell plus live read-only APIs only",async()=>{const root=createRepo(),viewer=await startViewer({root,port:0,open:false});try{assert.equal(viewer.host,"127.0.0.1");const page=await fetch(viewer.url);assert.equal(page.status,200);assert.match(await page.text(),/Repository Intelligence Prototype v47/);for(const asset of ["/viewer-base.css","/viewer-surfaces.css","/viewer-0.js","/viewer-5.js"])assert.equal((await fetch(new URL(asset,viewer.url))).status,404);const first=await fetch(new URL("/api/index",viewer.url)).then(r=>r.json());assert.equal(first.ok,true);assert.equal(first.index.generated.edges.some(e=>e.type==="imports"),true);const meta=await fetch(new URL("/api/meta",viewer.url)).then(r=>r.json());assert.equal(meta.display_name,"example/repoaxis-viewer-fixture");assert.equal(meta.host_label,"GitHub");const history=await fetch(new URL("/api/history",viewer.url)).then(r=>r.json());assert.equal(history.commit.subject,"update util and remove legacy");assert.equal(history.changes.some(c=>c.path==="src/legacy.js"&&c.status==="D"),true);const health=await fetch(new URL("/api/health",viewer.url)).then(r=>r.json());assert.deepEqual(health,{ok:true,repository:".",host:"127.0.0.1"});fs.writeFileSync(path.join(root,"src","util.js"),"export const value = 3;\n");const second=await fetch(new URL("/api/index",viewer.url)).then(r=>r.json());assert.equal(second.index.generated.nodes["file:src/util.js"].git.working,"modified");for(const endpoint of ["/api/index","/api/meta","/api/history"])assert.equal((await fetch(new URL(endpoint,viewer.url),{method:"POST"})).status,405)}finally{await new Promise(resolve=>viewer.server.close(resolve))}});
