import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { startViewer } from "../../../skills/repoaxis/lib/view-server.mjs";

const SKILL_DIR=fileURLToPath(new URL("../../../skills/repoaxis/",import.meta.url));
const VIEWER_DIR=path.join(SKILL_DIR,"viewer"),VIEWER_HTML=path.join(VIEWER_DIR,"repoaxis.html"),LIVE_MARK="<!-- LIVE REPOSITORY DATA -->";
const INTERNAL_IDENTIFIER=/\b[A-Za-z_$][\w$]*(?:V|R)\d+[A-Za-z0-9_$]*\b/;
const INTERNAL_ITERATION_COMMENT=/(?:\/\*|\/\/|<!--)\s*[vVrR]\d+(?:\.\d+)*\b/;
const INTERNAL_FILENAME=/(?:^|[-_.])(?:v|r)\d+(?:[-_.]\d+)*(?:[-_.]|$)/i;
function git(root,...args){return execFileSync("git",["-C",root,...args],{encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim()}
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const p=path.join(dir,e.name);return e.isDirectory()?walk(p):[p]})}
function createRepo(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"repoaxis-viewer-"));fs.mkdirSync(path.join(root,"src"),{recursive:true});fs.writeFileSync(path.join(root,"src","util.js"),"export const value = 1;\n");fs.writeFileSync(path.join(root,"src","main.js"),"import { value } from './util.js';\nexport function main(){ return value; }\n");fs.writeFileSync(path.join(root,"src","legacy.js"),"export const legacy = true;\n");git(root,"init","-q","-b","main");git(root,"config","user.name","Repoaxis Viewer Test");git(root,"config","user.email","repoaxis@example.invalid");git(root,"remote","add","origin","git@github.com:example/repoaxis-viewer-fixture.git");git(root,"add",".");git(root,"commit","-qm","fixture");fs.writeFileSync(path.join(root,"src","util.js"),"export const value = 2;\n");fs.rmSync(path.join(root,"src","legacy.js"));git(root,"add","-A");git(root,"commit","-qm","update util and remove legacy");return root}

test("product filenames and viewer runtime contain no internal development version codes",()=>{for(const file of walk(SKILL_DIR)){const rel=path.relative(SKILL_DIR,file);assert.doesNotMatch(rel,INTERNAL_FILENAME,`internal version code in product filename: ${rel}`)}const html=fs.readFileSync(VIEWER_HTML,"utf8");assert.doesNotMatch(html,INTERNAL_IDENTIFIER);assert.doesNotMatch(html,INTERNAL_ITERATION_COMMENT)});

test("viewer is a single-file shell whose repository state comes only from live APIs",()=>{assert.deepEqual(fs.readdirSync(VIEWER_DIR).sort(),["repoaxis.html"]);const html=fs.readFileSync(VIEWER_HTML,"utf8");assert.ok(html.indexOf(LIVE_MARK)>0);assert.match(html,/<title>Repoaxis — Repository Intelligence<\/title>/);assert.match(html,/data-repoaxis-live=["']loading["']/);for(const id of ["structureStage","dependenciesStage","changesStage","graphStage","drawer"])assert.match(html,new RegExp(`id="${id}"`));for(const fn of ["renderOverview","renderDependencies","renderChanges","renderGraph","navigateSelectedTo","openChangeSetGraph","impactPaths","bootRepository"])assert.match(html,new RegExp(`function ${fn}|${fn}=function`));assert.match(html,/fetch\('\/api\/index'\)/);assert.match(html,/fetch\('\/api\/meta'\)/);assert.match(html,/fetch\('\/api\/history'\)/);assert.match(html,/let repositoryReady=false/);assert.match(html,/repositoryReady=true;\s*applyHash\(\)/);assert.match(html,/const tree=\[\{id:'root',parent:null,type:'root'/);assert.match(html,/const importEdges=\[\]/);assert.match(html,/const changes=\[\]/);assert.match(html,/const workingChanges=changes\.map/);assert.match(html,/const lastCommitChanges=\[\]/);assert.match(html,/let graphClusters=\[\]/);assert.doesNotMatch(html,/renderOverview\(\);renderFocus\(\);renderDependencies\(\);renderChanges\(\);renderGraph\(\);renderDrawer\(\);applyHash\(\)/);for(const forbidden of ["byId.config","src/index.js","src/cli.js","src/worker.js","config/default.json","deprecated-loader.js","Repository Intelligence Prototype"])assert.equal(html.includes(forbidden),false,`fixture/prototype residue: ${forbidden}`);assert.match(html,/canonicalRoot=raw\.find/);assert.match(html,/function overviewVisibleBBox\(/);assert.match(html,/document\.querySelectorAll\(['"]#overviewSvg \.overview-node['"]\)\.forEach/);assert.match(html,/function frameChangeSetRoots\(/);assert.match(html,/function structureFocusScope\(/);assert.match(html,/function frameGraphSelection\(/);assert.doesNotMatch(html,/(?:src|href)="\/viewer-/);for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>new Function(m[1]))});

test("viewer server serves the shell plus live read-only APIs only",async()=>{const root=createRepo(),viewer=await startViewer({root,port:0,open:false});try{assert.equal(viewer.host,"127.0.0.1");const page=await fetch(viewer.url);assert.equal(page.status,200);const html=await page.text();assert.match(html,/Repoaxis — Repository Intelligence/);assert.doesNotMatch(html,/Repository Intelligence Prototype/);for(const asset of ["/viewer-base.css","/viewer-surfaces.css","/viewer-0.js","/viewer-5.js"])assert.equal((await fetch(new URL(asset,viewer.url))).status,404);const first=await fetch(new URL("/api/index",viewer.url)).then(r=>r.json());assert.equal(first.ok,true);assert.equal(first.index.generated.edges.some(e=>e.type==="imports"),true);const meta=await fetch(new URL("/api/meta",viewer.url)).then(r=>r.json());assert.equal(meta.display_name,"example/repoaxis-viewer-fixture");assert.equal(meta.host_label,"GitHub");const history=await fetch(new URL("/api/history",viewer.url)).then(r=>r.json());assert.equal(history.commit.subject,"update util and remove legacy");assert.equal(history.changes.some(c=>c.path==="src/legacy.js"&&c.status==="D"),true);const health=await fetch(new URL("/api/health",viewer.url)).then(r=>r.json());assert.deepEqual(health,{ok:true,repository:".",host:"127.0.0.1"});fs.writeFileSync(path.join(root,"src","util.js"),"export const value = 3;\n");const second=await fetch(new URL("/api/index",viewer.url)).then(r=>r.json());assert.equal(second.index.generated.nodes["file:src/util.js"].git.working,"modified");for(const endpoint of ["/api/index","/api/meta","/api/history"])assert.equal((await fetch(new URL(endpoint,viewer.url),{method:"POST"})).status,405)}finally{await new Promise(resolve=>viewer.server.close(resolve))}});
